---
# tasks file for roles/nagiosmain_centos
- name: download and extract nagios from official website
  unarchive:
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    remote_src: yes

- name: configure nagios on centos
  command: ./configure --with-command-group=nagiosxi
  args:
    chdir: /tmp/nagios-4.4.5

- name: configure make clean
  make:
    target: clean
    chdir: /tmp/nagios-4.4.5

- name: configure make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5

- name: configure make install
  make:
    target: install
    chdir: /tmp/nagios-4.4.5

- name: configure make install-init
  make:
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: configure make install-daemoinit
  make:
    target: install-daemoninit
    chdir: /tmp/nagios-4.4.5

- name: configure make insta-config
  make:
    target: install-config
    chdir: /tmp/nagios-4.4.5

- name: configure make install-commandmode
  make:
    target: install-commandmode
    chdir: /tmp/nagios-4.4.5

- name: configure make install-exfoliation
  make:
    target: install-exfoliation
    chdir: /tmp/nagios-4.4.5

- name: install webconf
  make:
    target: install-webconf
    chdir: /tmp/nagios-4.4.5

- name: install passlib
  pip:
    name: passlib

- name: create user to authenticate
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: user
    password: password

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
